### ISSUE TITLE
USER STORY:  As an attendee, I want to view a list of upcoming events so that I can decide which event to attend.

### ISSUE THREAD

**Issue by Ojay97-hub** [Ojay97-hub/event-scheduler#1]
EPIC: Event List (Read)

As a **attendee** I can **view a list of upcoming events** so that **I can decide which event to attend**

**Acceptance Criteria**

- [x] The attendee can see a list of events, sorted by date.
- [x] Each event shows a brief summary (title, date, and location).

**Tasks**

- [x] 1. Design the event list UI.
- [x] 2. Implement event fetching API.
- [x] 3. Sort events by date.
- [x] 4. Display title, date, and location.
- [x] 5. Create user authentication to allow personal login
