### ISSUE TITLE
USER STORY: As an organiser, I want to update the event details so that I can reflect any changes.

### ISSUE THREAD

**Issue by Ojay97-hub** [Ojay97-hub/event-scheduler#10]
EPIC: Edit Events (Update)

As a **event organiser** I can **update event details** so that I **can reflect any changes to the event**

**Acceptance Criteria**

- [x] Organisers can successfully update event details through an edit form.
- [x] The event’s updated information is reflected immediately

**Tasks**

- [x] 1. Create event edit form.
- [x] 2. Pre-fill form with existing event data.
- [x] 3. Implement update API.
- [x] 4. Reflect changes immediately in the event list and details page.
