### ISSUE TITLE
USER STORY: As an organiser, I want to delete an event that is no longer happening so that attendees can be notified.

### ISSUE THREAD

**Issue by Ojay97-hub** [Ojay97-hub/event-scheduler#11]
EPIC: Delete Events (Delete)

As a **organiser** I can **delete an event that is no longer happening** so that **attendees can be notified.**

**Acceptance Criteria**

- [x] Organisers can delete an event.
- [x] Attendees who registered receive a cancellation notification.

**Tasks**

- [x] 1. Create delete option in the event list.
- [x] 2. Implement event deletion API.
- [x] 3. Notify registered attendees of cancellation.
