### ISSUE TITLE
USER STORY: As an organiser, I want to view a list of people who have registered for an event so I can see and contact who is attending.

### ISSUE THREAD

**Issue by Ojay97-hub** [Ojay97-hub/event-scheduler#12]
EPIC: Attendee List (Read)

As a **organiser** I can **view a list of people who have registered for an event** so that **I can see and contact who is attending.**

**Acceptance Criteria**

- [x] Organisers can view the list of attendees registered for each event.
- [x] The list includes attendee names and emails.

**Tasks**

- [x] 1. Create an attendee list page.
- [x] 2. Fetch registered attendees from the database.
- [x] 3. Display attendee names and emails.
