### ISSUE TITLE
USER STORY: As an organiser, I want to mark an event as "Full" once it reaches maximum capacity so that registrations are disenabled.

### ISSUE THREAD

**Issue by Ojay97-hub** [Ojay97-hub/event-scheduler#13]
EPIC: Capacity Management (Update)

As a **organiser** I can **mark an event as "Full" once it reaches maximum capacity** so that **registrations are disenabled**

**Acceptance Criteria**

- [ ] The event is automatically marked as "Full" when registration reaches capacity.
- [ ] No more registrations can be made after it's full.

**Tasks**

- [ ] 1. Set capacity limits for events.
- [ ] 2. Implement automatic status change when capacity is reached.
- [ ] 3. Disable registration for full events.

**Comment by Ojay97-hub** [comment]
the capacity is already set to ensure the event is full once it is has reached maximum capacity with another user story
