### ISSUE TITLE
USER STORY: As an organiser, I want to search and filter events based on status, date, or category and organiser, so that I can analyse potential competitors.

### ISSUE THREAD

**Issue by Ojay97-hub** [Ojay97-hub/event-scheduler#14]
EPIC: Search & Filter (Read)

As a **organiser** I can **search and filter events based on status, date, or category and organiser** so that **I can analyse potential competitors.**

**Acceptance Criteria**

- [x] Organisers can search and filter events by date, category, or status as well as organiser.
- [x] The filtered events list displays the correct information.

**Tasks**

- [x] 1. Create search and filter UI for organisers.
- [x] 2. Implement search functionality.
- [x] 3. Implement filtering based on status, date, or category and organiser.
- [x] 4. Display filtered results.
