### ISSUE TITLE
USER STORY: As an admin, I want to view a list of all events on the platform, so that I can moderate event entries to maintain platform quality. 

### ISSUE THREAD

**Issue by Ojay97-hub** [Ojay97-hub/event-scheduler#15]
EPIC: Global Event Overview (Read

As a **admin** I can **view a list of all events on the platform** so that **I can moderate event entries to maintain platform quality**

**Acceptance Criteria**

- [x] Admin can view a list of all events across the platform, including title, date, and status.
- [x] Admin can accept or decline events with edit and delete capabilities. 
- [x] Attendees and organisers receive a notification when an event is deleted.

**Tasks**

- [x] 1. Create a global event list UI.
- [x] 2. Fetch all platform events from the database.
- [x] 3. Display title, date, and status of events.
- [x] 4. Add functionalities of accept or decline events with edit/delete options.
- [x] 5. Notify attendees and organisers of deleted events.
