### ISSUE TITLE
USER STORY: As an admin, I want to filter or search through all events on the platform so that I can quickly access events that require attention.

### ISSUE THREAD

**Issue by Ojay97-hub** [Ojay97-hub/event-scheduler#16]
EPIC: Search & Filter (Read)

As a **admin** I can **filter or search through all events on the platform** so that **I can quickly access events that require attention.**

**Acceptance Criteria**

- [x] Admin can search by keywords or filter events by status, category, or date.
- [x] The filtered list displays correct information.

**Tasks**

- [x] 1. Create search and filter UI for admin.
- [x] 2. Implement global search and filtering by status, category, or date.
- [x] 3. Display filtered events correctly.
