### ISSUE TITLE
As an event attendee, I would like to write comments under the event detail to discuss with other attendees and leave positive reviews

### ISSUE THREAD

**Issue by Ojay97-hub** [Ojay97-hub/event-scheduler#17]
Write Comments (CRUD)

As a **event attendee** I can **write comments under the event detail** so that **discussions and reviews can take place**

**Acceptance Criteria**

1. Event attendees can create comments on event detail pages.
2. Event attendees can view a list of comments under the event detail.
3. Event attendees can edit their own comments.
4. Event attendees can delete their own comments.
5. Comments are linked to the event and user that posted them.
6. Only logged-in users can post, edit, or delete comments.

**Tasks**

- [x] Create the model
- [x] Create the form
- [x] Update the event detail template
- [x] Update the urls.py file
