### ISSUE TITLE
USER STORY: As an attendee, I want to view the details of a specific event so that I can learn more about it.

### ISSUE THREAD

**Issue by Ojay97-hub** [Ojay97-hub/event-scheduler#2]
EPIC: Event Details (Read)

As a **attendee** I can **view the details of a specific event** so that **I can learn more about it.**

**Acceptance Criteria**

- [x] Clicking on an event from the list shows details (description, date, time, location, capacity).

**Tasks**

- [x] 1. Create an event details page.
- [x] 2. Fetch event data based on user click.
- [x] 3. Display event details (description, time, etc.).
