### ISSUE TITLE
Epic 2: Event Registration and Management for Attendees

### ISSUE THREAD

**Issue by Ojay97-hub** [Ojay97-hub/event-scheduler#20]
As an **attendee**, I want to **manage my event registrations** so that I can **track my commitments and make changes** as needed.

**User Stories Tasks:**

- [x] 	Register for an event: #3
- [x] View a list of events I have registered for: #4
- [x] Cancel my registration if I can no longer attend: #6
