### ISSUE TITLE
Epic 3: Event Creation and Management for Organisers

### ISSUE THREAD

**Issue by Ojay97-hub** [Ojay97-hub/event-scheduler#21]
As an **organiser**, I want to **create, manage, and oversee my events** so that I can **engage attendees and ensure successful event execution**.

**User Stories Tasks**:

- [x]  Create a new event: #8
- [x] 	View a list of all events I’ve created: #9
- [x] Update the event details: #10
- [x] Delete an event that is no longer happening:	#11
- [x] View a list of people who have registered for an event: #12
