### ISSUE TITLE
USER STORY: As an attendee, I want to register for an event so that I can reserve a spot.

### ISSUE THREAD

**Issue by Ojay97-hub** [Ojay97-hub/event-scheduler#3]
EPIC: Event Registration (Create)

As a **attendee** I can **register for an event** so that **I can reserve a spot**

**Acceptance Criteria**

- [x] Attendees can register with an email.
- [x] Confirmation message appears upon successful registration.

**Tasks**

- [x] 1. Create a registration form.
- [x] 2. Implement form validation.
- [x] 3. Display confirmation message upon successful submission.
