### ISSUE TITLE
USER STORY: As an attendee, I want to search for specific events by category or status so that I can speed up my search

### ISSUE THREAD

**Issue by Ojay97-hub** [Ojay97-hub/event-scheduler#5]
EPIC: Search & Filter (Read)

As a **attendee** I can **search for specific events by category or status** so that **I can speed up my search**

**Acceptance Criteria**

- [x] The attendee can use a filter by keywords, location, date, and categories.
- [x] Filters display relevant events.

**Tasks**

- [x] 1. Create search and filter UI.
- [x] 2. Implement search functionality.
- [x] 3. Implement filtering by category, location, and status.
- [x] 4. Return filtered event list.
