### ISSUE TITLE
USER STORY: As an attendee, I want to cancel my registration if I can no longer attend so that I can release my spot.

### ISSUE THREAD

**Issue by Ojay97-hub** [Ojay97-hub/event-scheduler#6]
EPIC: Cancel Registration (Delete)

As a **attendee** I can **cancel my registration if I can no longer attend** so that **I can release my spot.**

**Acceptance Criteria**

- [x] Attendees can cancel their registration.
- [x] Confirmation message appears, and the event is removed from the registered events list.

**Tasks**

- [x] 1. Create a cancel button on the registered events list.
- [x] 2. Implement cancel registration API.
- [x] 3. Display confirmation message.
- [x] 4. Remove the event from the user's list.
