### ISSUE TITLE
USER STORY: As an organiser, I want to create a new event so that people can register for it.

### ISSUE THREAD

**Issue by Ojay97-hub** [Ojay97-hub/event-scheduler#8]
EPIC: Create Events (Create)

As a **organiser** I can **create a new event** so that **people can register for it**

**Acceptance Criteria**

- [x] Organisers can fill in a form with event details and submit it.
- [x] The event appears in the event list after creation.

**Tasks**

- [x] 1. Create event creation form.
- [x] 2. Validate form fields.
- [x] 3. Implement event creation API.
- [x] 4. Ensure new events appear in the list.
