### ISSUE TITLE
USER STORY: As an organiser, I want to view a list of all events I’ve created so that I can manage them efficiently.

### ISSUE THREAD

**Issue by Ojay97-hub** [Ojay97-hub/event-scheduler#9]
EPIC: Organiser's Event List (Read)

As a **organiser** I can **view a list of all events I’ve created** so that **I can manage them efficiently.**

**Acceptance Criteria**

- [x] Organisers can see a list of events they’ve created, including title, date, time, and registration status.

**Tasks**

- [x] 1. Create an organiser's event list page.
- [x] 2. Fetch organiser’s events from the database.
- [x] 3. Display title, date, time, and registration status.
